// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// BookInterface is an autogenerated mock type for the BookInterface type
type BookInterface struct {
	mock.Mock
}

// ReadBook provides a mock function with given fields:
func (_m *BookInterface) ReadBook() {
	_m.Called()
}
