// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RedisInterface is an autogenerated mock type for the RedisInterface type
type RedisInterface struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *RedisInterface) Close() {
	_m.Called()
}

// Get provides a mock function with given fields: key
func (_m *RedisInterface) Get(key string) string {
	ret := _m.Called(key)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Ping provides a mock function with given fields:
func (_m *RedisInterface) Ping() {
	_m.Called()
}

// Set provides a mock function with given fields: key, value
func (_m *RedisInterface) Set(key string, value string) {
	_m.Called(key, value)
}
